//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuartoApp.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuartoApp.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Développeur/Chef de projet.
        /// </summary>
        internal static string AngeRole {
            get {
                return ResourceManager.GetString("AngeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Charger.
        /// </summary>
        internal static string Charger {
            get {
                return ResourceManager.GetString("Charger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coloré.
        /// </summary>
        internal static string Colored {
            get {
                return ResourceManager.GetString("Colored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Crédits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Difficile.
        /// </summary>
        internal static string Difficile {
            get {
                return ResourceManager.GetString("Difficile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Egalite.
        /// </summary>
        internal static string Egalite {
            get {
                return ResourceManager.GetString("Egalite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer un pseudo.
        /// </summary>
        internal static string EntrerPseudo {
            get {
                return ResourceManager.GetString("EntrerPseudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Facile.
        /// </summary>
        internal static string Facile {
            get {
                return ResourceManager.GetString("Facile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Développeur/Chef de projet/Concepteur backend.
        /// </summary>
        internal static string GabrielRole {
            get {
                return ResourceManager.GetString("GabrielRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Général.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Développeuse/Cheffe de projet/Graphiste.
        /// </summary>
        internal static string InesRole {
            get {
                return ResourceManager.GetString("InesRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jouer ►.
        /// </summary>
        internal static string Jouer {
            get {
                return ResourceManager.GetString("Jouer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Joueur 1.
        /// </summary>
        internal static string LoginJoueur1 {
            get {
                return ResourceManager.GetString("LoginJoueur1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Joueur 2.
        /// </summary>
        internal static string LoginJoueur2 {
            get {
                return ResourceManager.GetString("LoginJoueur2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moderne.
        /// </summary>
        internal static string Modern {
            get {
                return ResourceManager.GetString("Modern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moyen.
        /// </summary>
        internal static string Moyen {
            get {
                return ResourceManager.GetString("Moyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres.
        /// </summary>
        internal static string Parametres {
            get {
                return ResourceManager.GetString("Parametres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir une langue.
        /// </summary>
        internal static string PickerText {
            get {
                return ResourceManager.GetString("PickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quarto !.
        /// </summary>
        internal static string Quarto {
            get {
                return ResourceManager.GetString("Quarto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter.
        /// </summary>
        internal static string Quitter {
            get {
                return ResourceManager.GetString("Quitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Règles.
        /// </summary>
        internal static string Regles {
            get {
                return ResourceManager.GetString("Regles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rejouer.
        /// </summary>
        internal static string Rejouer {
            get {
                return ResourceManager.GetString("Rejouer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour.
        /// </summary>
        internal static string Retour {
            get {
                return ResourceManager.GetString("Retour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarder.
        /// </summary>
        internal static string Sauvegarder {
            get {
                return ResourceManager.GetString("Sauvegarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Score.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Simple.
        /// </summary>
        internal static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Victoire.
        /// </summary>
        internal static string Victoire {
            get {
                return ResourceManager.GetString("Victoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Volume de la musique.
        /// </summary>
        internal static string Volume_de_la_musique {
            get {
                return ResourceManager.GetString("Volume de la musique", resourceCulture);
            }
        }
    }
}
